=== Amsterdam/amsterdam-schema/schema@v4.1.0/scope.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://schemas.data.amsterdam.nl/scope@v4.1.0",
  "type": "object",
  "required": [
    "name",
    "id",
    "type",
    "owner",
    "accessPackages"
  ],
  "properties": {
    "type": {
      "const": "scope"
    },
    "name": {
      "description": "Naam van de scope.",
      "type": "string",
      "minLength": 1
    },
    "id": {
      "description": "ID van de scope.",
      "type": "string",
      "minLength": 1,
      "maxLength": 32,
      "pattern": "[A-Za-z/]"
    },
    "accessPackages": {
      "description": "Object met omgevingen en hun bijbehorende Access Packages.",
      "type": "object",
      "properties": {
        "production": {
          "description": "Access Package voor de productieomgeving.",
          "type": "string"
        },
        "nonProduction": {
          "description": "Access Package voor de niet-productieomgeving.",
          "type": "string"
        }
      },
      "additionalProperties": {
        "type": "string"
      }
    },
    "owner": {
      "description": "id van het team dat de data beheert in de DataHub (doorgaans het datateam). Zie /publishers voor de mogelijke ids.",
      "type": "object",
      "required": [
        "$ref"
      ],
      "properties": {
        "$ref": {
          "type": "string",
          "format": "uri-reference"
        },
        "additionalProperties": false
      }
    }
  }
}

=== Amsterdam/amsterdam-schema/scopes/AMID/topdeskbv_msi.json
{
    "type": "scope",
    "id": "TOPDESKBV/MSI",
    "name": "topdeskbv/msi",
    "accessPackages": {
        "production": "EM4W-DATA-schemascope-p-scope_topdeskbv_msi",
        "nonProduction": "EM4W-DATA-schemascope-ot-scope_topdeskbv_msi"
    },
    "owner": {
        "$ref": "publishers/AMID"
    }
}

=== Amsterdam/amsterdam-schema/scopes/SVD/klachtenafhandelingdvl.json
{
  "type": "scope",
  "id": "KLACHTENAFHANDELINGDVL",
  "name": "Klachtenafhandeling Dienstverlening",
  "accessPackages": {
    "nonProduction": "EM4W-DATA-schemascope-ot-scope_klachtenafhandelingdvl",
    "production": "EM4W-DATA-schemascope-p-scope_klachtenafhandelingdvl"
  },
  "owner": {
    "$ref": "publishers/SVD"
  }
}

=== Amsterdam/amsterdam-schema/scopes/SVD/juridischbureausociaal.json
{
  "type": "scope",
  "id": "JURIDISCHBUREAUSOCIAAL",
  "name": "Juridisch Bureau Sociaal",
  "accessPackages": {
    "nonProduction": "EM4W-DATA-schemascope-ot-scope_juridischbureausociaal",
    "production": "EM4W-DATA-schemascope-p-scope_juridischbureausociaal"
  },
  "owner": {
    "$ref": "publishers/SVD"
  }
}
